name: Clojure CI

on: [push]

jobs:
  build:
    name: Test on java ${{ matrix.java }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '8', '11', '12' ]
        os: [ubuntu-latest] #[ubuntu-latest,  macOS-latest]

    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java Action
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Install Clojure
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.739.sh
        chmod +x linux-install-1.10.1.739.sh
        sudo ./linux-install-1.10.1.739.sh
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
