name: Clojure CI

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '1.8', '9.0.x', '12.0.2' ]
        os: [ubuntu-latest] #[ubuntu-latest,  macOS-latest]

    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        java-version: ${{ matrix.java }}
    - name: Install Clojure
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
        chmod +x linux-install-1.10.1.469.sh
        sudo ./linux-install-1.10.1.469.sh
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
